### ISSUE TITLE
امکان کم و زیاد کردن سرعت حین دانلود یا قبل از شروع عملیات

### ISSUE THREAD

**Issue by LinArcX** [alireza-amirsamimi/pdmt#5]
سلام و عرض ادب خدمت علیرضای گل و خسته نباشید جانانه بابت کارت
چند تا پیشنهاد دارم فک کنم به درد بخوره..حداقل واسه من که دارم از پی.دی.ام.تی استفاده میکنم فک میکنم کاربردی باشه:
1-قبل از اینکه عملیات دانلود شروع بشه یا دیالوگ مثلا توی ترمینال باز بشه و از کاربر بخواد حداقل و حداکثر سرعت رو تعیین کنه و هم چنین ساعت اتمام دانلود
2-در حین عملیات دانلود بشه منویی تعبیه کرد که سرعت رو کم و زیاد کرد در همون  لحظه یا اگه کاربر میخواد وسط کار بتونه عملیات بعد از اتمام  کار رو تعیین کنه.

**Comment by alireza-amirsamimi** [comment]
سلام
توی ورژن جدید اضافه کردم :)
