### ISSUE TITLE
No icon in toolbar

### ISSUE THREAD

**Issue by molaeiali** [alireza-amirsamimi/pdmt#6]
Installed form AUR persepolis-git 2.0.2_unstable.r22.gca235a5-2
Installed dependancies for arch that you noticed
I think it needs archdroid icon theme as a dependancy, tried to install it from AUR but needs thise packages 
ttf-roboto
ttf-roboto-font
ttf-google-fonts-git
ttf-google-fonts-hg
otf-google-fonts-hg
that seems removed and installation fails!
![persepolis-report](https://cloud.githubusercontent.com/assets/12999682/17297411/dc8595da-581a-11e6-8ea5-449f5d9b1547.png)

**Comment by alireza-amirsamimi** [comment]
سلام نه نیازی به اون پیش نیازهایی که گفتید نیست
میزکارتون چی هست؟
یه لطف میکنی برنامه ای که با 
aur
نصب کردی رو کامل از نصب خارج کنی و با
git clone
یا با دستوراتی که گفتم نصب کنی و نتیجه رو به من بگی
ممنونم

**Comment by molaeiali** [comment]
خب من البته یه اشتباه کردم که مشکل رو برای ورژن ۱ گزارش کردم
ورژن ۲ رو با
git clone
هم گرفتم، همین مشکل هست
میزکارم
xfce
هست

**Comment by alireza-amirsamimi** [comment]
عجیبه
منم از
Arch + xfce
استفاده میکنم و هیچ مشکلی ندارم
با
pyqt5
آشنا هستی یه کد رو برات بفرستم اجرا کنی و تست کنی؟

**Comment by molaeiali** [comment]
حدس زدم شاید مشکل از آیکون‌هام باشه و... همه چیز رو دیفالت کردم جواب نگرفتم، با
pyqt5
آشنا نیستم ولی خب راهنمایی کنی اجرا می‌کنم کدت رو نتیجه رو می‌گم!
می‌شه منتقل کرد این پیام‌ها رو به مشکلات ورژن ۲؟
حس می‌کنم کار خوبی نیست اینجا این بحث انجام می‌شه

**Comment by alireza-amirsamimi** [comment]
این کد رو به یه اسم توی 
home
ذخیره کن
مثلا
foo.py

`#!/usr/bin/python3
# -*- coding: utf-8 -*-



import sys
from PyQt5.QtWidgets import (QWidget, QPushButton, QApplication)
from PyQt5.QtGui import QIcon


class Example(QWidget):
    
    def __init__(self):
        super().__init__()
        
        
        self.btn = QPushButton('Button', self)
        self.btn.move(50, 50)       
        self.btn.setIcon(QIcon.fromTheme('exit'))
        
        self.setGeometry(300, 300, 300, 200)
        
        self.show()
        
        
if __name__ == '__main__':
    
    app = QApplication(sys.argv)
    ex = Example()
    sys.exit(app.exec_())
`

بهش با زدن این کد توی ترمینال قابلیت اجرایی بده
`chmod +x foo.py`

حالا اینجوری توی ترمینال اجراش کن
`./foo.py`
ببین وقتی اجرا میشه آیکنی نمایش میده کنار 
button
جوابش رو توی ورژن جدید بنویس
ممنونم
